import { DEMO_IDS } from "./fixtureIds.js";

export const DEFAULT_DEMO_DATA_AS_OF =
  "2026-07-26T18:42:00.000Z";

const money = (amountMinor, currency = "USD") => ({
  amount_minor: amountMinor,
  currency,
});

const freshness = () => ({
  synced_at: DEFAULT_DEMO_DATA_AS_OF,
  status: "fresh",
});

export function buildDefaultAccounts() {
  return [
    {
      id: "account_checking",
      institution_id: "institution_seacomm",
      institution_name: "Seacomm Federal Credit Union",
      name: "Everyday checking",
      mask: "4821",
      type: "depository",
      subtype: "checking",
      balance_group: "cash",
      current_balance: money(845_329),
      available_balance: money(815_329),
      is_liability: false,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_savings",
      institution_id: "institution_seacomm",
      institution_name: "Seacomm Federal Credit Union",
      name: "High-yield savings",
      mask: "1038",
      type: "depository",
      subtype: "savings",
      balance_group: "cash",
      current_balance: money(3_642_451),
      available_balance: money(3_642_451),
      is_liability: false,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_sapphire",
      institution_id: "institution_chase",
      institution_name: "Chase",
      name: "Sapphire Preferred",
      mask: "9204",
      type: "credit",
      subtype: "credit_card",
      balance_group: "credit_card",
      current_balance: money(193_240),
      available_balance: money(506_760),
      credit_limit: money(700_000),
      is_liability: true,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_brokerage",
      institution_id: "institution_vanguard",
      institution_name: "Vanguard",
      name: "Brokerage",
      mask: "7714",
      type: "investment",
      subtype: "brokerage",
      balance_group: "taxable_investment",
      current_balance: money(6_342_941),
      available_balance: null,
      is_liability: false,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_roth",
      institution_id: "institution_vanguard",
      institution_name: "Vanguard",
      name: "Roth IRA",
      mask: "3009",
      type: "investment",
      subtype: "roth",
      balance_group: "retirement",
      current_balance: money(2_694_508),
      available_balance: null,
      is_liability: false,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_401k",
      institution_id: "institution_fidelity",
      institution_name: "Fidelity",
      name: "401(k)",
      mask: "2881",
      type: "investment",
      subtype: "401k",
      balance_group: "retirement",
      current_balance: money(3_330_100),
      available_balance: null,
      is_liability: false,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_personal_loan",
      institution_id: "institution_seacomm",
      institution_name: "Seacomm Federal Credit Union",
      name: "Personal loan",
      mask: "6418",
      type: "loan",
      subtype: "personal",
      balance_group: "loan",
      current_balance: money(1_618_327),
      available_balance: null,
      is_liability: true,
      active: true,
      freshness: freshness(),
    },
    {
      id: "account_amex",
      institution_id: "institution_amex",
      institution_name: "American Express",
      name: "Blue Cash Preferred",
      mask: "1184",
      type: "credit",
      subtype: "credit_card",
      balance_group: "credit_card",
      current_balance: money(88_223),
      available_balance: money(411_777),
      credit_limit: money(500_000),
      is_liability: true,
      active: true,
      freshness: freshness(),
    },
  ];
}

function transactionAccount(accountById, id, name = null) {
  const account = accountById.get(id);
  if (!account) {
    throw new TypeError(`Unknown default demo account: ${id}`);
  }
  return {
    id: account.id,
    name: name ?? account.name,
    mask: account.mask,
    institution: account.institution_name,
  };
}

export function buildDefaultTransactions() {
  const accountById = new Map(
    buildDefaultAccounts().map((account) => [account.id, account]),
  );
  const checking = () =>
    transactionAccount(accountById, "account_checking");
  const savings = () =>
    transactionAccount(accountById, "account_savings");
  const sapphire = () =>
    transactionAccount(accountById, "account_sapphire");
  return [
    {
      id: DEMO_IDS.transactions.wholeFoods,
      date: "2026-07-25",
      posted_on: "2026-07-25",
      posted_at: "2026-07-25T20:34:00.000Z",
      merchant: "Whole Foods Market",
      description: "Whole Foods Market",
      raw_merchant: "WHOLE FOODS MKT #1024",
      raw_name: "WHOLE FOODS MKT #1024",
      display_name: "Whole Foods Market",
      note: "Dinner supplies for the family visit",
      note_version: 1,
      note_updated_by: "demo-user",
      note_updated_at: "2026-07-25T21:10:00.000Z",
      category: "Groceries",
      category_primary: "Groceries",
      tags: ["Household"],
      account: checking(),
      amount: money(-13_842),
      icon: "ph-shopping-cart",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: DEMO_IDS.transactions.conEdison,
      date: "2026-07-25",
      merchant: "Con Edison",
      description: "Con Edison",
      display_name: "Con Edison",
      category: "Utilities",
      category_primary: "Utilities",
      tags: [],
      account: checking(),
      amount: money(-18_419),
      icon: "ph-lightning",
      pending: true,
      excluded_from_spending: false,
    },
    {
      id: DEMO_IDS.transactions.appleServices,
      date: "2026-07-24",
      posted_on: "2026-07-24",
      merchant: "Apple Services",
      description: "AAPL SRV 0042",
      display_name: "Apple Services",
      category: "Subscriptions",
      category_primary: "Subscriptions",
      tags: [],
      account: sapphire(),
      amount: money(-2_803),
      icon: "ph-device-mobile",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_004",
      date: "2026-07-24",
      merchant: "Blue Bottle Coffee",
      description: "Blue Bottle Coffee",
      display_name: "Blue Bottle Coffee",
      category: "Dining",
      category_primary: "Dining",
      tags: [],
      account: sapphire(),
      amount: money(-1_275),
      icon: "ph-coffee",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: DEMO_IDS.transactions.payroll,
      date: "2026-07-23",
      merchant: "Acme Payroll",
      description: "Payroll deposit",
      display_name: "Acme Payroll",
      category: "Income",
      category_primary: "Income",
      tags: [],
      account: checking(),
      amount: money(465_000),
      icon: "ph-buildings",
      pending: false,
      excluded_from_spending: true,
    },
    {
      id: "txn_006",
      date: "2026-07-22",
      merchant: "MTA OMNY",
      description: "MTA OMNY",
      display_name: "MTA OMNY",
      category: "Transportation",
      category_primary: "Transportation",
      tags: [],
      account: sapphire(),
      amount: money(-3_400),
      icon: "ph-train",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_007",
      date: "2026-07-21",
      merchant: "Fidelis Care",
      description: "Fidelis Care",
      display_name: "Fidelis Care",
      category: "Bills",
      category_primary: "Bills",
      tags: [],
      account: checking(),
      amount: money(-40_804),
      icon: "ph-heartbeat",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: DEMO_IDS.transactions.delta,
      date: "2026-07-20",
      merchant: "Delta Air Lines",
      description: "Delta Air Lines",
      display_name: "Delta Air Lines",
      category: "Travel",
      category_primary: "Travel",
      tags: [],
      account: sapphire(),
      amount: money(-48_620),
      icon: "ph-airplane-tilt",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_009",
      date: "2026-07-19",
      merchant: "Target",
      description: "Target",
      display_name: "Target",
      category: "Shopping",
      category_primary: "Shopping",
      tags: [],
      account: sapphire(),
      amount: money(-8_639),
      icon: "ph-shopping-bag",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: DEMO_IDS.transactions.googleWorkspace,
      date: "2026-07-18",
      merchant: "Google Workspace",
      description: "Google Workspace",
      display_name: "Google Workspace",
      category: "Subscriptions",
      category_primary: "Subscriptions",
      tags: [],
      account: checking(),
      amount: money(-8_564),
      icon: "ph-browser",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_011",
      date: "2026-07-18",
      merchant: "Seacomm Transfer",
      description: "Seacomm Transfer",
      display_name: "Seacomm Transfer",
      category: "Transfer",
      category_primary: "Transfer",
      tags: [],
      account: savings(),
      amount: money(60_000),
      icon: "ph-arrows-left-right",
      pending: false,
      excluded_from_spending: true,
    },
    {
      id: "txn_012",
      date: "2026-07-17",
      merchant: "Trader Joe's",
      description: "Trader Joe's",
      display_name: "Trader Joe's",
      category: "Groceries",
      category_primary: "Groceries",
      tags: [],
      account: checking(),
      amount: money(-7_694),
      icon: "ph-basket",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_013",
      date: "2026-07-16",
      merchant: "Seacomm Overdraft Fee",
      description: "Seacomm Overdraft Fee",
      display_name: "Seacomm Overdraft Fee",
      category: "Fees & Interest",
      category_primary: "Fees & Interest",
      tags: [],
      account: checking(),
      amount: money(-3_500),
      icon: "ph-coins",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: DEMO_IDS.transactions.wellsFargoAuto,
      date: "2026-07-16",
      posted_on: "2026-07-16",
      merchant: "Wells Fargo Auto",
      description: "WELLS FARGO AUTO DRAFT 260716",
      display_name: "Wells Fargo Auto",
      category: "Car / Auto Loan",
      category_primary: "Car / Auto Loan",
      tags: [],
      account: checking(),
      amount: money(-100_000),
      icon: "ph-car",
      pending: false,
      excluded_from_spending: true,
      cash_flow_role: "obligation",
    },
    {
      id: "txn_014",
      date: "2026-07-15",
      merchant: "Personal Loan Interest",
      description: "Personal Loan Interest",
      display_name: "Personal Loan Interest",
      category: "Fees & Interest",
      category_primary: "Fees & Interest",
      tags: [],
      account: checking(),
      amount: money(-8_100),
      icon: "ph-coins",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_015",
      date: "2026-07-14",
      merchant: "Whole Foods Mkt 117",
      description: "WHOLEFDS MKT 117 BROOKLYN",
      raw_merchant: "WHOLEFDS MKT 117",
      raw_name: "WHOLEFDS MKT 117 BROOKLYN",
      display_name: "Whole Foods Mkt 117",
      category: "Groceries",
      category_primary: "Groceries",
      tags: [],
      account: sapphire(),
      amount: money(-6_249),
      icon: "ph-shopping-cart",
      pending: false,
      excluded_from_spending: false,
    },
    {
      id: "txn_016",
      date: "2026-07-09",
      merchant: "Whole Foods Market",
      description: "WHOLE FOODS MARKET 1024",
      raw_merchant: "WHOLE FOODS MARKET",
      raw_name: "WHOLE FOODS MARKET 1024",
      display_name: "Whole Foods Market",
      category: "Groceries",
      category_primary: "Groceries",
      tags: ["Food"],
      account: checking(),
      amount: money(-9_184),
      icon: "ph-shopping-cart",
      pending: false,
      excluded_from_spending: false,
    },
  ];
}

export function buildDefaultRecurringPayments() {
  const accountById = new Map(
    buildDefaultAccounts().map((account) => [account.id, account]),
  );
  const account = (id) => {
    const value = accountById.get(id);
    if (!value) {
      throw new TypeError(`Unknown recurring demo account: ${id}`);
    }
    return { id: value.id, name: value.name };
  };
  const recurring = ({
    id,
    service,
    serviceFamily,
    type,
    amountMinor,
    nextEstimatedDate,
    accountId,
    icon,
    category,
    cashFlowRole = "spending",
    confidenceBasisPoints = 9_000,
    classificationSignals = null,
    transactions = [],
  }) => ({
    id,
    service,
    service_family: serviceFamily,
    type,
    detected_type: type,
    cadence: "monthly",
    expected_amount: money(amountMinor),
    monthly_equivalent: money(amountMinor),
    annual_equivalent: money(amountMinor * 12),
    next_estimated_date: nextEstimatedDate,
    confidence_basis_points: confidenceBasisPoints,
    status: "active",
    account: account(accountId),
    icon,
    category,
    cash_flow_role: cashFlowRole,
    classification_signals:
      classificationSignals ?? {
        occurrence_count: 6,
        interval_fit_basis_points: 9_500,
        amount_variation_basis_points: 250,
        classification_confidence_basis_points:
          confidenceBasisPoints,
      },
    transactions,
  });
  return [
    recurring({
      id: DEMO_IDS.recurring.googleWorkspace,
      service: "Google Workspace",
      serviceFamily: "google_workspace",
      type: "subscription",
      amountMinor: 8_564,
      nextEstimatedDate: "2026-08-18",
      accountId: "account_checking",
      icon: "ph-browser",
      category: "Software & services",
      confidenceBasisPoints: 9_900,
      classificationSignals: {
        subscription_signal: true,
        occurrence_count: 7,
        interval_fit_basis_points: 10_000,
        amount_variation_basis_points: 0,
        classification_confidence_basis_points: 9_900,
      },
      transactions: [
        {
          id: DEMO_IDS.transactions.googleWorkspace,
          merchant: "Google Workspace",
          date: "2026-07-18",
          amount: money(-8_564),
        },
      ],
    }),
    recurring({
      id: DEMO_IDS.recurring.adobe,
      service: "Adobe Creative Cloud",
      serviceFamily: "adobe_creative_cloud",
      type: "subscription",
      amountMinor: 6_999,
      nextEstimatedDate: "2026-08-03",
      accountId: "account_sapphire",
      icon: "ph-bezier-curve",
      category: "Software & services",
    }),
    recurring({
      id: DEMO_IDS.recurring.appleServices,
      service: "Apple Services",
      serviceFamily: "apple_services",
      type: "subscription",
      amountMinor: 2_803,
      nextEstimatedDate: "2026-08-24",
      accountId: "account_sapphire",
      icon: "ph-device-mobile",
      category: "Software & services",
    }),
    recurring({
      id: DEMO_IDS.recurring.squarespace,
      service: "Squarespace Website",
      serviceFamily: "squarespace",
      type: "subscription",
      amountMinor: 2_500,
      nextEstimatedDate: "2026-08-08",
      accountId: "account_checking",
      icon: "ph-squares-four",
      category: "Software & services",
    }),
    recurring({
      id: DEMO_IDS.recurring.disneyPlus,
      service: "Disney+",
      serviceFamily: "disney_plus",
      type: "subscription",
      amountMinor: 1_999,
      nextEstimatedDate: "2026-08-11",
      accountId: "account_sapphire",
      icon: "ph-television",
      category: "Entertainment",
    }),
    recurring({
      id: DEMO_IDS.recurring.iCloud,
      service: "iCloud+",
      serviceFamily: "icloud",
      type: "subscription",
      amountMinor: 999,
      nextEstimatedDate: "2026-08-14",
      accountId: "account_sapphire",
      icon: "ph-cloud",
      category: "Software & services",
    }),
    recurring({
      id: DEMO_IDS.recurring.fidelis,
      service: "Fidelis Care",
      serviceFamily: "fidelis_care",
      type: "bill",
      amountMinor: 40_804,
      nextEstimatedDate: "2026-08-21",
      accountId: "account_checking",
      icon: "ph-heartbeat",
      category: "Health",
      confidenceBasisPoints: 9_400,
    }),
    recurring({
      id: DEMO_IDS.recurring.conEdison,
      service: "Con Edison",
      serviceFamily: "con_edison",
      type: "bill",
      amountMinor: 18_419,
      nextEstimatedDate: "2026-08-25",
      accountId: "account_checking",
      icon: "ph-lightning",
      category: "Utilities",
    }),
    recurring({
      id: DEMO_IDS.recurring.verizonFios,
      service: "Verizon Fios",
      serviceFamily: "verizon_fios",
      type: "bill",
      amountMinor: 8_999,
      nextEstimatedDate: "2026-08-09",
      accountId: "account_sapphire",
      icon: "ph-wifi-high",
      category: "Utilities",
    }),
    recurring({
      id: DEMO_IDS.recurring.geico,
      service: "GEICO",
      serviceFamily: "geico",
      type: "bill",
      amountMinor: 14_622,
      nextEstimatedDate: "2026-08-15",
      accountId: "account_checking",
      icon: "ph-car",
      category: "Insurance",
    }),
    recurring({
      id: DEMO_IDS.recurring.wellsFargoAuto,
      service: "Wells Fargo Auto",
      serviceFamily: "wells_fargo_auto",
      type: "bill",
      amountMinor: 100_000,
      nextEstimatedDate: "2026-08-16",
      accountId: "account_checking",
      icon: "ph-car-profile",
      category: "Car / Auto Loan",
      cashFlowRole: "obligation",
      confidenceBasisPoints: 10_000,
      transactions: [
        {
          id: DEMO_IDS.transactions.wellsFargoAuto,
          merchant: "Wells Fargo Auto",
          date: "2026-07-16",
          amount: money(-100_000),
          category: "Car / Auto Loan",
        },
      ],
    }),
    recurring({
      id: DEMO_IDS.recurring.shell,
      service: "Shell Oil",
      serviceFamily: "shell_oil",
      type: "frequent_spending",
      amountMinor: 4_820,
      nextEstimatedDate: null,
      accountId: "account_sapphire",
      icon: "ph-gas-pump",
      category: "Transportation",
      classificationSignals: {
        hard_negative: true,
        occurrence_count: 4,
        interval_fit_basis_points: 8_000,
        amount_variation_basis_points: 900,
        classification_confidence_basis_points: 9_000,
      },
    }),
  ];
}

export function buildDefaultPortfolioHoldings() {
  return [
    {
      id: DEMO_IDS.holdings.vti,
      security_id: "security_vti",
      account_id: "account_brokerage",
      ticker_symbol: "VTI",
      name: "Vanguard Total Stock Market ETF",
      security_type: "equity",
      value_minor: 3_827_442,
      start_value_minor: 3_720_000,
      week_change_minor: 30_000,
      cost_basis_minor: 3_050_400,
      price_minor: 258_262,
      price_as_of: "2026-07-26",
      change_percent: 2.4,
      quantity: 14.82,
      shares_label: "14.82",
    },
    {
      id: DEMO_IDS.holdings.vxus,
      security_id: "security_vxus",
      account_id: "account_brokerage",
      ticker_symbol: "VXUS",
      name: "Vanguard Total International Stock ETF",
      security_type: "equity",
      value_minor: 2_455_810,
      start_value_minor: 2_370_000,
      week_change_minor: 18_000,
      cost_basis_minor: 1_943_400,
      price_minor: 63_937,
      price_as_of: "2026-07-26",
      change_percent: 1.1,
      quantity: 38.41,
      shares_label: "38.41",
    },
    {
      id: DEMO_IDS.holdings.vmfxx,
      security_id: "security_vmfxx",
      account_id: "account_brokerage",
      ticker_symbol: "VMFXX",
      name: "Vanguard Federal Money Market",
      security_type: "cash",
      value_minor: 59_689,
      start_value_minor: 60_000,
      week_change_minor: 3_000,
      cost_basis_minor: 59_689,
      price_minor: 100,
      price_as_of: "2026-07-26",
      change_percent: 0.1,
      quantity: 596.89,
      shares_label: "596.89",
    },
    {
      id: DEMO_IDS.holdings.bnd,
      security_id: "security_bnd",
      account_id: "account_roth",
      ticker_symbol: "BND",
      name: "Vanguard Total Bond Market ETF",
      security_type: "fixed_income",
      value_minor: 2_061_884,
      start_value_minor: 2_000_000,
      week_change_minor: 12_000,
      cost_basis_minor: 1_640_000,
      price_minor: 73_770,
      price_as_of: "2026-07-26",
      change_percent: -0.3,
      quantity: 27.95,
      shares_label: "27.95",
    },
    {
      id: DEMO_IDS.holdings.aapl,
      security_id: "security_aapl",
      account_id: "account_roth",
      ticker_symbol: "AAPL",
      name: "Apple Inc.",
      security_type: "equity",
      value_minor: 1_790_441,
      start_value_minor: 1_750_000,
      week_change_minor: 15_000,
      cost_basis_minor: 1_435_000,
      price_minor: 211_636,
      price_as_of: "2026-07-26",
      change_percent: 3.8,
      quantity: 8.46,
      shares_label: "8.46",
    },
    {
      id: DEMO_IDS.holdings.target,
      security_id: "security_target",
      account_id: "account_401k",
      ticker_symbol: "TARGET",
      display_symbol: "Other",
      name: "Retirement target-date fund",
      display_name: "Retirement target-date funds",
      security_type: "mixed",
      value_minor: 2_172_283,
      start_value_minor: 2_128_449,
      week_change_minor: 10_420,
      cost_basis_minor: 1_745_400,
      price_minor: null,
      price_as_of: "2026-07-26",
      change_percent: 0.7,
      quantity: 31.02,
      shares_label: "—",
    },
  ];
}

export function buildDefaultPlanningAccounts() {
  return buildDefaultAccounts().map((account) => ({
    id: account.id,
    type: account.type,
    subtype: account.subtype,
    balance_group: account.balance_group,
    current_balance_minor:
      account.current_balance?.amount_minor ?? null,
    currency_code: account.current_balance?.currency ?? "USD",
    active: account.active !== false,
  }));
}

export function buildDefaultGoals() {
  return [
    {
      id: "goal_down_payment",
      name: "House down payment",
      target_amount_minor: 10_000_000,
      currency_code: "USD",
      target_on: "2029-06-01",
      purpose: "home",
      status: "active",
      archived_at: null,
      archive_outcome: null,
      version: 1,
      allocations: [
        { source: "cash", amount_minor: 500_000 },
        { source: "brokerage", amount_minor: 1_500_000 },
      ],
      recorded_allocations: [
        { source: "cash", amount_minor: 500_000 },
        { source: "brokerage", amount_minor: 1_500_000 },
      ],
      spending: [],
      schedules: [
        {
          id: "schedule_down_payment",
          goal_id: "goal_down_payment",
          source: "brokerage",
          cadence: "monthly",
          amount_minor: 100_000,
          monthly_day: 15,
          anchor_on: null,
          next_run_on: "2026-08-15",
          status: "active",
          version: 1,
        },
      ],
    },
    {
      id: "goal_car_mods",
      name: "Car modifications",
      target_amount_minor: 1_200_000,
      currency_code: "USD",
      target_on: "2027-08-01",
      purpose: "vehicle",
      status: "active",
      archived_at: null,
      archive_outcome: null,
      version: 1,
      allocations: [{ source: "cash", amount_minor: 250_000 }],
      recorded_allocations: [
        { source: "cash", amount_minor: 250_000 },
      ],
      spending: [],
      schedules: [
        {
          id: "schedule_car_mods",
          goal_id: "goal_car_mods",
          source: "cash",
          cadence: "biweekly_friday",
          amount_minor: 20_000,
          monthly_day: null,
          anchor_on: "2026-07-31",
          next_run_on: "2026-07-31",
          status: "active",
          version: 1,
        },
      ],
    },
    {
      id: "goal_summer_vacation",
      name: "Summer vacation",
      purpose: "vacation",
      target_amount_minor: 300_000,
      currency_code: "USD",
      target_on: "2026-07-15",
      status: "archived",
      archived_at: "2026-07-24T18:00:00.000Z",
      archive_outcome: "completed",
      version: 2,
      allocations: [],
      recorded_allocations: [
        { source: "cash", amount_minor: 300_000 },
      ],
      spending: [{ source: "cash", amount_minor: 330_000 }],
      schedules: [],
    },
    {
      id: "goal_beach_getaway",
      name: "Beach getaway",
      purpose: "vacation",
      target_amount_minor: 200_000,
      currency_code: "USD",
      target_on: "2025-08-10",
      status: "archived",
      archived_at: "2025-08-18T18:00:00.000Z",
      archive_outcome: "completed",
      version: 2,
      allocations: [],
      recorded_allocations: [
        { source: "cash", amount_minor: 200_000 },
      ],
      spending: [{ source: "cash", amount_minor: 216_000 }],
      schedules: [],
    },
    {
      id: "goal_family_road_trip",
      name: "Family road trip",
      purpose: "vacation",
      target_amount_minor: 150_000,
      currency_code: "USD",
      target_on: "2024-07-20",
      status: "archived",
      archived_at: "2024-07-28T18:00:00.000Z",
      archive_outcome: "completed",
      version: 2,
      allocations: [],
      recorded_allocations: [
        { source: "cash", amount_minor: 150_000 },
      ],
      spending: [{ source: "cash", amount_minor: 168_000 }],
      schedules: [],
    },
  ];
}

export function buildDefaultBudgetDefaults() {
  return new Map([
    ["Housing", 145_000],
    ["Groceries", 75_000],
    ["Dining", 45_000],
    ["Shopping", 40_000],
    ["Travel", 50_000],
    ["Utilities", 40_000],
    ["Fees & Interest", 5_000],
    ["Other", 20_000],
  ]);
}

export function buildDefaultBudgetActuals({
  previousMonth = false,
} = {}) {
  return new Map([
    ["Housing", 145_000],
    ["Groceries", 68_430],
    ["Dining", previousMonth ? 46_000 : 52_146],
    ["Shopping", 47_890],
    ["Travel", 41_205],
    ["Utilities", 33_913],
    ["Fees & Interest", 11_600],
    ["Other", 12_500],
  ]);
}
