export const DEMO_IDS = Object.freeze({
  transactions: Object.freeze({
    wholeFoods: "txn_whole_foods",
    conEdison: "txn_con_edison",
    appleServices: "txn_apple_services",
    delta: "txn_delta_1",
    googleWorkspace: "txn_google_workspace",
    payroll: "txn_payroll",
  }),
  recurring: Object.freeze({
    googleWorkspace: "rec_google_workspace",
    adobe: "rec_adobe",
    appleServices: "rec_apple_services",
    squarespace: "rec_squarespace",
    disneyPlus: "rec_disney_plus",
    iCloud: "rec_icloud",
    fidelis: "rec_fidelis",
    conEdison: "rec_con_edison",
    verizonFios: "rec_verizon_fios",
    geico: "rec_geico",
    shell: "rec_shell",
  }),
  holdings: Object.freeze({
    vti: "holding_vti",
    vxus: "holding_vxus",
    vmfxx: "holding_vmfxx",
    bnd: "holding_bnd",
    aapl: "holding_aapl",
    target: "holding_target",
  }),
  insights: Object.freeze({
    weeklyDining: "ins_week_001",
    weeklyCoffee: "ins_week_002",
    weeklyTravel: "ins_week_003",
    investmentPerformance: "ins_inv_001",
    investmentConcentration: "ins_inv_002",
    subscriptionDuplicate: "ins_sub_001",
    subscriptionExpensive: "ins_sub_002",
    archivedWeeklyDining: "ins_week_archive_001",
    archivedSubscriptionDuplicate: "ins_sub_archive_001",
  }),
});
